#ifndef MCONFIG_H
#define MCONFIG_H

#define SERIAL_HIGH_PRIORITY_QUEUE_SIZE    128
#define SERIAL_MEDIUM_PRIORITY_QUEUE_SIZE  256
#define SERIAL_LOW_PRIORITY_QUEUE_SIZE     256
#define SERIAL_TRANSFER_PACKETS_PER_LOOP   2

#endif 