apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api
  name: api
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8000
    - name: "5456"
      port: 5456
      targetPort: 5456
  selector:
    app: api
status:
  loadBalancer: {}
