apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodeserver
  name: nodeserver
spec:
  ports:
    - name: "3009"
      port: 3009
      targetPort: 3001
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    app: nodeserver
status:
  loadBalancer: {}
