apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    app: nodeserver
  name: nodeserver
spec:
  replicas: 1
  selector:
    app: nodeserver
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodeserver
    spec:
      containers:
        - args:
            - node
            - middleman.js
          image: ' '
          name: nodeserver
          ports:
            - containerPort: 3001
            - containerPort: 4000
          resources: {}
          volumeMounts:
            - mountPath: /code
              name: nodeserver-claim0
      hostname: nodeserver
      restartPolicy: Always
      volumes:
        - name: nodeserver-claim0
          persistentVolumeClaim:
            claimName: nodeserver-claim0
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - nodeserver
        from:
          kind: ImageStreamTag
          name: nodeserver:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
