apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    app: nodeserver
  name: nodeserver
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: nodeserver
      generation: null
      importPolicy: {}
      name: ""
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
