#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER CHSUser1 WITH PASSWORD 'A9EQFT6gS#LRHHwo75MRPZQl8mWaA02N&';
	CREATE DATABASE SensorData;
	GRANT ALL PRIVILEGES ON DATABASE SensorData TO CHSUser1;
EOSQL

