apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
  namespace: ne
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "5456"
      port: 5456
      targetPort: 5456
  selector:
    app: api
status:
  loadBalancer: {}
