apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: nelab/neapi
          name: api
          ports:
            - containerPort: 8000
            - containerPort: 5456
          resources:
            requests:
              memory: "64Mi"
              cpu: "500m"
            limits:
              memory: "64Mi"
              cpu: "500m"