apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeserver
  name: nodeserver
  namespace: ne
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    app: nodeserver