apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeserver
  name: nodeserver-nodeport
  namespace: ne
spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30006
  selector:
    app: nodeserver