apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
  namespace: ne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodeserver
    spec:
      containers:
        - args:
            - node
            - middleman.js
          image: nelab/nenode:latest
          name: nodeserver
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "64Mi"
              cpu: "500m"
            limits:
              memory: "64Mi"
              cpu: "500m"
