# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: nelab/nedb:latest
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
          env:
            - name: POSTGRES_USER
              value: CHSUser1
            - name: POSTGRES_PASSWORD
              value: A9EQFT6gS#LRHHwo75MRPZQl8mWaA02N&
            - name: POSTGRES_DB
              value: SensorData
            # - name: PGDATA
            #   value: /data/pgdata
          # Config from ConfigMap
          #envFrom:
          #- configMapRef:
          #    name: postgres-db-config
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi